#ifndef NMSG_SIE_DEFS_H
#define NMSG_SIE_DEFS_H

#define NMSG_VENDOR_SIE_DNSDEDUPE_ID	1
#define NMSG_VENDOR_SIE_DNSDEDUPE_NAME	"dnsdedupe"

#define NMSG_VENDOR_SIE_REPUTATION_ID	2
#define NMSG_VENDOR_SIE_REPUTATION_NAME	"reputation"

#define NMSG_VENDOR_SIE_QR_ID		3
#define NMSG_VENDOR_SIE_QR_NAME		"qr"

#define NMSG_VENDOR_SIE_DELAY_ID	4
#define NMSG_VENDOR_SIE_DELAY_NAME	"delay"

#define NMSG_VENDOR_SIE_NEWDOMAIN_ID	5
#define NMSG_VENDOR_SIE_NEWDOMAIN_NAME	"newdomain"

#define NMSG_VENDOR_SIE_DNSNX_ID	6
#define NMSG_VENDOR_SIE_DNSNX_NAME	"dnsnx"

#endif /* NMSG_SIE_DEFS_H */
